fix(local-env): setup cyclotorn node

diff --git a/bin/migrate b/bin/migrate
--- a/bin/migrate
+++ b/bin/migrate
@@ -41,6 +41,13 @@ if [ -d "$SCRIPT_DIR/../rust/bin" ] && [ "${DEPLOYMENT:-}" != "hobby" ]; then
         fi
     fi
 
+    if run_scope "cyclotron-node"; then
+        bash $SCRIPT_DIR/../rust/bin/migrate-cyclotron-node
+        if [ $? -ne 0 ]; then
+            echo "Error in rust/bin/migrate-cyclotron-node, exiting."
+            exit 1
+        fi
+    fi
 
     if run_scope "behavioral-cohorts"; then
         echo "Running behavioral cohorts migrations via external non-django migrator..."
