Added other DB migration

diff --git a/bin/migrate b/bin/migrate
--- a/bin/migrate
+++ b/bin/migrate
@@ -31,6 +31,12 @@ if [ -d "$SCRIPT_DIR/../rust/bin" ] && [ "${DEPLOYMENT:-}" != "hobby" ]; then
             echo "Error in rust/bin/migrate-cyclotron, exiting."
             exit 1
         fi
+
+        bash $SCRIPT_DIR/../rust/bin/migrate-cyclotron-node
+        if [ $? -ne 0 ]; then
+            echo "Error in rust/bin/migrate-cyclotron-node, exiting."
+            exit 1
+        fi
     fi
     
     if run_scope "cyclotron-shadow"; then
