fix(msg): fix health check and add to bin/migrate (#35680)

diff --git a/bin/migrate b/bin/migrate
--- a/bin/migrate
+++ b/bin/migrate
@@ -13,6 +13,17 @@ if [ -d "$SCRIPT_DIR/../rust/bin" ]; then
     fi
 fi
 
+# Run Cassandra migrations if the migrate-cassandra script exists
+if [ -f "$SCRIPT_DIR/../plugin-server/bin/migrate-cassandra" ]; then
+    bash $SCRIPT_DIR/../plugin-server/bin/migrate-cassandra
+    if [ $? -ne 0 ]; then
+        echo "Error in plugin-server/bin/migrate-cassandra, exiting."
+        exit 1
+    fi
+fi
+
+
+
 # Create a temporary file for background process status
 # Ensure cleanup of temp file on script exit
 trap 'rm -f "$CLICKHOUSE_STATUS" 2>/dev/null' EXIT
