some cleanup

diff --git a/bin/migrate b/bin/migrate
--- a/bin/migrate
+++ b/bin/migrate
@@ -12,12 +12,12 @@ if [ -d "$SCRIPT_DIR/../rust/bin" ]; then
         exit 1
     fi
     
-		echo "Running persons migrations via external non-django migrator..."
-		bash $SCRIPT_DIR/../rust/bin/migrate-persons
-		if [ $? -ne 0 ]; then
-				echo "Error in rust/bin/migrate-persons, exiting."
-				exit 1
-		fi
+    echo "Running persons migrations via external non-django migrator..."
+    bash $SCRIPT_DIR/../rust/bin/migrate-persons
+    if [ $? -ne 0 ]; then
+        echo "Error in rust/bin/migrate-persons, exiting."
+        exit 1
+    fi
 fi
 
 # Create a temporary file for background process status
