feat(cyclotron): add shadow service

diff --git a/bin/migrate b/bin/migrate
--- a/bin/migrate
+++ b/bin/migrate
@@ -26,6 +26,14 @@ if [ -d "$SCRIPT_DIR/../rust/bin" ]; then
         fi
     fi
 
+    if run_scope "cyclotron-shadow"; then
+        bash $SCRIPT_DIR/../rust/bin/migrate-cyclotron-shadow
+        if [ $? -ne 0 ]; then
+            echo "Error in rust/bin/migrate-cyclotron-shadow, exiting."
+            exit 1
+        fi
+    fi
+
     if run_scope "persons"; then
         echo "Running persons migrations via external non-django migrator..."
         bash $SCRIPT_DIR/../rust/bin/migrate-persons
