restart plugin server if killed

diff --git a/bin/plugin-server b/bin/plugin-server
--- a/bin/plugin-server
+++ b/bin/plugin-server
@@ -1,4 +1,7 @@
 #!/bin/bash
+# this makes the script exit if `yarn --frozen-lockfile` fails
+set -e
+
 KEYS="DATABASE_URL REDIS_URL PLUGINS_CELERY_QUEUE CELERY_DEFAULT_QUEUE BASE_DIR PLUGINS_RELOAD_PUBSUB_CHANNEL"
 
 # Export $CONFIG to posthog-plugin-server
@@ -14,4 +17,10 @@ if [[ -n "${DYNO_RAM}" ]]; then
   export WORKER_CONCURRENCY=$(( ($DYNO_RAM - 1) / 512 + 1 ))
 fi
 
-cd plugins && yarn --frozen-lockfile --silent && yarn --silent start
+cd plugins
+yarn --frozen-lockfile --silent
+
+while true; do
+  # break loop if exiting normally (incl CTRL+C)
+  yarn --silent start && break
+done
