Fix

diff --git a/go/Makefile b/go/Makefile
--- a/go/Makefile
+++ b/go/Makefile
@@ -16,6 +16,31 @@ build:
 		fi \
 	done
 
+run-%:
+	@if [ -f services/$*/main.go ]; then \
+		cd services/$* && go run .; \
+	else \
+		echo "Service $* not found"; \
+		exit 1; \
+	fi
+
+build-%:
+	@if [ -f services/$*/main.go ]; then \
+		echo "Building services/$*..."; \
+		cd services/$* && go build -o ../../bin/$*; \
+	else \
+		echo "Service $* not found"; \
+		exit 1; \
+	fi
+
+test-%:
+	@if [ -d services/$* ]; then \
+		cd services/$* && go test ./...; \
+	else \
+		echo "Service $* not found"; \
+		exit 1; \
+	fi
+
 clean:
 	rm -rf bin/
 	find . -name "*.test" -delete 
