add cleanup script for _sqlx_test databases left over from failed runs

diff --git a/rust/bin/util b/rust/bin/util
--- a/rust/bin/util
+++ b/rust/bin/util
@@ -3,7 +3,7 @@
 SQLX_CLI_VERSION="0.8.3"
 POSTHOG_DOCKER_DB_CONTAINER_NAME="posthog-db-1"
 
-function log() {
+function log {
   set +x
   if [[ "${1:-}" == "--err" ]]; then
     shift 1
@@ -14,7 +14,7 @@ function log() {
   set -x
 }
 
-function check_docker_compose_up() {
+function check_docker_compose_up {
   log "Checking on Docker Compose and DB container: ${POSTHOG_DOCKER_DB_CONTAINER_NAME}..."
 
   if [[ -z "$(docker ps -q -f "name=${POSTHOG_DOCKER_DB_CONTAINER_NAME}")" ]] ; then
@@ -23,7 +23,7 @@ function check_docker_compose_up() {
   fi
 }
 
-function check_install_pinned_sqlx_cli() {
+function check_install_pinned_sqlx_cli {
   log "Checking SQLX CLI is installed at version ${SQLX_CLI_VERSION}..."
 
   if ! which sqlx; then
@@ -32,10 +32,16 @@ function check_install_pinned_sqlx_cli() {
   fi
 }
 
-function check_pg_dump_installed() {
+function check_pg_dump_installed {
   if ! which pg_dump; then
     log --err "Required: pg_dump tool must be installed locally"
     exit 1
   fi
 }
 
+function check_psql_installed {
+  if ! which psql; then
+    log --err "Required: psql tool must be installed locally"
+    exit 1
+  fi
+}
