add pg_dump schema export to bin/ scripts

diff --git a/rust/bin/util b/rust/bin/util
--- a/rust/bin/util
+++ b/rust/bin/util
@@ -18,16 +18,24 @@ function check_docker_compose_up() {
   log "Checking on Docker Compose and DB container: ${POSTHOG_DOCKER_DB_CONTAINER_NAME}..."
 
   if [[ -z "$(docker ps -q -f "name=${POSTHOG_DOCKER_DB_CONTAINER_NAME}")" ]] ; then
-    log --err "posthog repo root docker-compose must be UP prior to running $(realpath $0)"
+    log --err "Required: posthog repo root docker-compose must be UP"
     exit 1
   fi
 }
 
 function check_install_pinned_sqlx_cli() {
-  log "Checking that SQLX CLI tool is installed at version ${SQLX_CLI_VERSION}..."
+  log "Checking SQLX CLI is installed at version ${SQLX_CLI_VERSION}..."
 
   if ! which sqlx; then
     log "Installing SQLX CLI tool..."
     cargo install sqlx-cli --version "$SQLX_CLI_VERSION"
   fi
 }
+
+function check_pg_dump_installed() {
+  if ! which pg_dump; then
+    log --err "Required: pg_dump tool must be installed locally"
+    exit 1
+  fi
+}
+
