chore(hogql): enable package publish

diff --git a/.github/workflows/build-hogql-parser-npm.yml b/.github/workflows/build-hogql-parser-npm.yml
--- a/.github/workflows/build-hogql-parser-npm.yml
+++ b/.github/workflows/build-hogql-parser-npm.yml
@@ -77,76 +77,76 @@ jobs:
                   path: common/hogql_parser/dist/
                   if-no-files-found: error
 
-    # publish-npm:
-    #     name: Publish on npm
-    #     needs: build-wasm
-    #     runs-on: ubuntu-24.04
-    #     permissions:
-    #         contents: read
-    #         id-token: write
-    #     steps:
-    #         - uses: actions/checkout@v6
+    publish-npm:
+        name: Publish on npm
+        needs: build-wasm
+        runs-on: ubuntu-24.04
+        permissions:
+            contents: read
+            id-token: write
+        steps:
+            - uses: actions/checkout@v6
 
-    #         - name: Download dist artifact
-    #           uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
-    #           with:
-    #               name: hogql-parser-dist
-    #               path: common/hogql_parser/dist
+            - name: Download dist artifact
+              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
+              with:
+                  name: hogql-parser-dist
+                  path: common/hogql_parser/dist
 
-    #         - name: Set up Node 24
-    #           uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
-    #           with:
-    #               node-version: 24
-    #               registry-url: https://registry.npmjs.org
+            - name: Set up Node 24
+              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
+              with:
+                  node-version: 24
+                  registry-url: https://registry.npmjs.org
 
-    #         - name: Publish package to npm
-    #           run: cd common/hogql_parser && npm publish --access public
-    #           env:
-    #               NODE_AUTH_TOKEN: ''
-    #               NPM_CONFIG_PROVENANCE: true
+            - name: Publish package to npm
+              run: cd common/hogql_parser && npm publish --access public
+              env:
+                  NODE_AUTH_TOKEN: ''
+                  NPM_CONFIG_PROVENANCE: true
 
-    #         # Use GitHub app token so Actions run after committing changes
-    #         - name: Get app token
-    #           id: app-token
-    #           uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
-    #           with:
-    #               app_id: ${{ secrets.GH_APP_POSTHOG_TESTS_APP_ID }}
-    #               private_key: ${{ secrets.GH_APP_POSTHOG_TESTS_PRIVATE_KEY }}
+            # Use GitHub app token so Actions run after committing changes
+            - name: Get app token
+              id: app-token
+              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
+              with:
+                  app_id: ${{ secrets.GH_APP_POSTHOG_TESTS_APP_ID }}
+                  private_key: ${{ secrets.GH_APP_POSTHOG_TESTS_PRIVATE_KEY }}
 
-    #         - uses: actions/checkout@v6
-    #           with:
-    #               ref: ${{ github.event.pull_request.head.ref }}
-    #               token: ${{ steps.app-token.outputs.token }}
+            - uses: actions/checkout@v6
+              with:
+                  ref: ${{ github.event.pull_request.head.ref }}
+                  token: ${{ steps.app-token.outputs.token }}
 
-    #         - name: Install pnpm
-    #           uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
+            - name: Install pnpm
+              uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
 
-    #         - name: Set up Node 24
-    #           uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
-    #           with:
-    #               node-version: 24
-    #               cache: 'pnpm'
+            - name: Set up Node 24
+              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
+              with:
+                  node-version: 24
+                  cache: 'pnpm'
 
-    #         - name: Update @posthog/hogql-parser in frontend
-    #           shell: bash
-    #           env:
-    #               RETRIES: 20
-    #           run: |
-    #               VERSION=$(node -p "require('./common/hogql_parser/package.json').version")
-    #               for i in $(seq 1 $RETRIES); do
-    #                   if pnpm --filter=@posthog/frontend add "@posthog/hogql-parser@$VERSION"; then
-    #                       break
-    #                   fi
-    #                   if [[ $i -eq $RETRIES ]]; then
-    #                     echo "Failed to update @posthog/hogql-parser in frontend"
-    #                     exit 1
-    #                   fi
-    #                   sleep 0.5
-    #               done
+            - name: Update @posthog/hogql-parser in frontend
+              shell: bash
+              env:
+                  RETRIES: 20
+              run: |
+                  VERSION=$(node -p "require('./common/hogql_parser/package.json').version")
+                  for i in $(seq 1 $RETRIES); do
+                      if pnpm --filter=@posthog/frontend add "@posthog/hogql-parser@$VERSION"; then
+                          break
+                      fi
+                      if [[ $i -eq $RETRIES ]]; then
+                        echo "Failed to update @posthog/hogql-parser in frontend"
+                        exit 1
+                      fi
+                      sleep 0.5
+                  done
 
-    #         - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
-    #           with:
-    #               add: '["frontend/package.json", "pnpm-lock.yaml"]'
-    #               message: 'Use new @posthog/hogql-parser npm version'
-    #               default_author: github_actions
-    #               github_token: ${{ steps.app-token.outputs.token }}
+            - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
+              with:
+                  add: '["frontend/package.json", "pnpm-lock.yaml"]'
+                  message: 'Use new @posthog/hogql-parser npm version'
+                  default_author: github_actions
+                  github_token: ${{ steps.app-token.outputs.token }}
