fix the Node.js Tests Pass job to actually fail on failure

diff --git a/.github/workflows/ci-nodejs.yml b/.github/workflows/ci-nodejs.yml
--- a/.github/workflows/ci-nodejs.yml
+++ b/.github/workflows/ci-nodejs.yml
@@ -262,5 +262,23 @@ jobs:
         needs: [tests, build, lint]
         name: Node.js Tests Pass
         runs-on: ubuntu-latest
+        if: always()
         steps:
             - run: exit 0
+            - name: Check outcomes
+              run: |
+                  if [[ "${{ needs.tests.result }}" != "success" ]]; then
+                    echo "One or more jobs in the Node.js test matrix failed."
+                    exit 1
+                  fi
+                  echo "All jobs in the Node.js test matrix passed."
+                  if [[ "${{ needs.build.result }}" != "success" ]]; then
+                    echo "Node.js build failed."
+                    exit 1
+                  fi
+                  echo "All jobs in the Node.js test matrix passed."
+                  if [[ "${{ needs.lint.result }}" != "success" ]]; then
+                    echo "Node.js lint failed."
+                    exit 1
+                  fi
+                  echo "All jobs in the Node.js test matrix passed."
